### ISSUE TITLE
Der Hangman wird nicht angezeigt

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [hhunderter/Hangman#1]
Hey, mir ist aufgefallen das der Hangman nicht angezeigt wird. Ich benutz PHP 8.1.

Es erscheint einfach nur sowas:
![image](https://github.com/hhunderter/Hangman/assets/11060723/bacc31d4-0fce-4120-96b9-5453410bbd87)

Ich hoffe auf ein schnellen fix um das Spiel in seiner Form genießen zu können. :)

**Comment by hhunderter** [comment]
Wenn du das Bild öffnest, erscheint dann ein Fehler?

**Comment by TheFrozenThr0ne** [comment]
Nein kommt kein fehler. Es erscheint wie gesagt als würde er das bild nicht finden oder existieren.
![image](https://github.com/hhunderter/Hangman/assets/11060723/0ead71ae-d1ee-4d97-a258-242ab063c30f)

Hab es auf 2 Webserver getestet. Einmal Strato PHP 8.1 und einmal bei mir Local mit PHP 8.2 glaub oderso...

**Comment by hhunderter** [comment]
Sollte behoben sein mit der neusten Version

**Comment by TheFrozenThr0ne** [comment]
Danke dir für den schnellen Fix. :) ❤

Funktioniert jetzt:
![image](https://github.com/hhunderter/Hangman/assets/11060723/4ef7c9ef-c88e-4d32-bc10-894f5f9f8dbf)
