### ISSUE TITLE
Kompatibilität Anpassungen für Bootstrap 5

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [hhunderter/Hangman#3]
Könntest du das bitte auf Bootstrap 5 aktualisieren das Modul?

Bei mir sind die Buchstaben in einer reihe und hab es auch nicht so richtig gemacht um ein Pull request zu eröffnen.

Grüße

**Comment by hhunderter** [comment]
Diese war schon vorhanden : https://github.com/hhunderter/Hangman/tree/BS5
habe es aber in den Master geschoben

**Comment by hhunderter** [comment]
Diese war schon vorhanden : https://github.com/hhunderter/Hangman/tree/BS5
habe es aber in den Master geschoben
